/* 
  MOVIES ACTIONS TYPES
*/

export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_MOVIES_REDUCER = "GET_POPULAR_MOVIES_REDUCER";

export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const SET_POPULAR_MOVIES_REDUCER = "SET_POPULAR_MOVIES_REDUCER";

export const GET_POPULAR_MOVIES_PAGE_REDUCER =
  "GET_POPULAR_MOVIES_PAGE_REDUCER";
export const SET_POPULAR_MOVIES_PAGE_REDUCER =
  "SET_POPULAR_MOVIES_PAGE_REDUCER";

export const GET_POPULAR_MOVIES_TOTAL_PAGES_REDUCER =
  "GET_POPULAR_MOVIES_TOTAL_PAGES_REDUCER";
export const SET_POPULAR_MOVIES_TOTAL_PAGES_REDUCER =
  "SET_POPULAR_MOVIES_TOTAL_PAGES_REDUCER";

export const GET_POPULAR_MOVIES_ERROR_REDUCER =
  "GET_POPULAR_MOVIES_ERROR_REDUCER";
export const SET_POPULAR_MOVIES_ERROR_REDUCER =
  "SET_POPULAR_MOVIES_ERROR_REDUCER";

export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_TOP_RATED_MOVIES_REDUCER = "GET_TOP_RATED_MOVIES_REDUCER";

export const SET_TOP_RATED_MOVIES = "SET_TOP_RATED_MOVIES";
export const SET_TOP_RATED_MOVIES_REDUCER = "SET_TOP_RATED_MOVIES_REDUCER";

export const GET_TOP_RATED_MOVIES_PAGE_REDUCER =
  "GET_TOP_RATED_MOVIES_PAGE_REDUCER";
export const SET_TOP_RATED_MOVIES_PAGE_REDUCER =
  "SET_TOP_RATED_MOVIES_PAGE_REDUCER";

export const GET_TOP_RATED_MOVIES_TOTAL_PAGES_REDUCER =
  "GET_TOP_RATED_MOVIES_TOTAL_PAGES_REDUCER";
export const SET_TOP_RATED_MOVIES_TOTAL_PAGES_REDUCER =
  "SET_TOP_RATED_MOVIES_TOTAL_PAGES_REDUCER";

export const GET_TOP_RATED_MOVIES_ERROR_REDUCER =
  "GET_TOP_RATED_MOVIES_ERROR_REDUCER";
export const SET_TOP_RATED_MOVIES_ERROR_REDUCER =
  "SET_TOP_RATED_MOVIES_ERROR_REDUCER";

export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_UPCOMING_MOVIES_REDUCER = "GET_UPCOMING_MOVIES_REDUCER";

export const SET_UPCOMING_MOVIES = "SET_UPCOMING_MOVIES";
export const SET_UPCOMING_MOVIES_REDUCER = "SET_UPCOMING_MOVIES_REDUCER";

export const GET_UPCOMING_MOVIES_PAGE_REDUCER =
  "GET_UPCOMING_MOVIES_PAGE_REDUCER";
export const SET_UPCOMING_MOVIES_PAGE_REDUCER =
  "SET_UPCOMING_MOVIES_PAGE_REDUCER";

export const GET_UPCOMING_MOVIES_TOTAL_PAGES_REDUCER =
  "GET_UPCOMING_MOVIES_TOTAL_PAGES_REDUCER";
export const SET_UPCOMING_MOVIES_TOTAL_PAGES_REDUCER =
  "SET_UPCOMING_MOVIES_TOTAL_PAGES_REDUCER";

export const GET_UPCOMING_MOVIES_ERROR_REDUCER =
  "GET_UPCOMING_MOVIES_ERROR_REDUCER";
export const SET_UPCOMING_MOVIES_ERROR_REDUCER =
  "SET_UPCOMING_MOVIES_ERROR_REDUCER";

export const GET_NOW_PLAYING_MOVIES = "GET_NOW_PLAYING_MOVIES";
export const GET_NOW_PLAYING_MOVIES_REDUCER = "GET_NOW_PLAYING_MOVIES_REDUCER";

export const SET_NOW_PLAYING_MOVIES = "SET_NOW_PLAYING_MOVIES";
export const SET_NOW_PLAYING_MOVIES_REDUCER = "SET_NOW_PLAYING_MOVIES_REDUCER";

export const GET_NOW_PLAYING_MOVIES_PAGE_REDUCER =
  "GET_NOW_PLAYING_MOVIES_PAGE_REDUCER";
export const SET_NOW_PLAYING_MOVIES_PAGE_REDUCER =
  "SET_NOW_PLAYING_MOVIES_PAGE_REDUCER";

export const GET_NOW_PLAYING_MOVIES_TOTAL_PAGES_REDUCER =
  "GET_NOW_PLAYING_MOVIES_TOTAL_PAGES_REDUCER";
export const SET_NOW_PLAYING_MOVIES_TOTAL_PAGES_REDUCER =
  "SET_NOW_PLAYING_MOVIES_TOTAL_PAGES_REDUCER";

export const GET_NOW_PLAYING_MOVIES_ERROR_REDUCER =
  "GET_NOW_PLAYING_MOVIES_ERROR_REDUCER";
export const SET_NOW_PLAYING_MOVIES_ERROR_REDUCER =
  "SET_NOW_PLAYING_MOVIES_ERROR_REDUCER";

/* 
  TV SHOWS ACTIONS TYPE
 */

export const GET_POPULAR_TV_SHOWS = "GET_POPULAR_TV_SHOWS";
export const GET_POPULAR_TV_SHOWS_REDUCER = "GET_POPULAR_TV_SHOWS_REDUCER";

export const SET_POPULAR_TV_SHOWS = "SET_POPULAR_TV_SHOWS";
export const SET_POPULAR_TV_SHOWS_REDUCER = "SET_POPULAR_TV_SHOWS_REDUCER";

export const GET_POPULAR_TV_SHOWS_PAGE_REDUCER =
  "GET_POPULAR_TV_SHOWS_PAGE_REDUCER";
export const SET_POPULAR_TV_SHOWS_PAGE_REDUCER =
  "SET_POPULAR_TV_SHOWS_PAGE_REDUCER";

export const GET_POPULAR_TV_SHOWS_TOTAL_PAGES_REDUCER =
  "GET_POPULAR_TV_SHOWS_TOTAL_PAGES_REDUCER";
export const SET_POPULAR_TV_SHOWS_TOTAL_PAGES_REDUCER =
  "SET_POPULAR_TV_SHOWS_TOTAL_PAGES_REDUCER";

export const GET_POPULAR_TV_SHOWS_ERROR_REDUCER =
  "GET_POPULAR_TV_SHOWS_ERROR_REDUCER";
export const SET_POPULAR_TV_SHOWS_ERROR_REDUCER =
  "SET_POPULAR_TV_SHOWS_ERROR_REDUCER";

export const GET_TOP_RATED_TV_SHOWS = "GET_TOP_RATED_TV_SHOWS";
export const GET_TOP_RATED_TV_SHOWS_REDUCER = "GET_TOP_RATED_TV_SHOWS_REDUCER";

export const SET_TOP_RATED_TV_SHOWS = "SET_TOP_RATED_TV_SHOWS";
export const SET_TOP_RATED_TV_SHOWS_REDUCER = "SET_TOP_RATED_TV_SHOWS_REDUCER";

export const GET_TOP_RATED_TV_SHOWS_PAGE_REDUCER =
  "GET_TOP_RATED_TV_SHOWS_PAGE_REDUCER";
export const SET_TOP_RATED_TV_SHOWS_PAGE_REDUCER =
  "SET_TOP_RATED_TV_SHOWS_PAGE_REDUCER";

export const GET_TOP_RATED_TV_SHOWS_TOTAL_PAGES_REDUCER =
  "GET_TOP_RATED_TV_SHOWS_TOTAL_PAGES_REDUCER";
export const SET_TOP_RATED_TV_SHOWS_TOTAL_PAGES_REDUCER =
  "SET_TOP_RATED_TV_SHOWS_TOTAL_PAGES_REDUCER";

export const GET_TOP_RATED_TV_SHOWS_ERROR_REDUCER =
  "GET_TOP_RATED_TV_SHOWS_ERROR_REDUCER";
export const SET_TOP_RATED_TV_SHOWS_ERROR_REDUCER =
  "SET_TOP_RATED_TV_SHOWS_ERROR_REDUCER";

export const GET_ON_AIRED_TV_SHOWS = "GET_ON_AIRED_TV_SHOWS";
export const GET_ON_AIRED_TV_SHOWS_REDUCER = "GET_ON_AIRED_TV_SHOWS_REDUCER";

export const SET_ON_AIRED_TV_SHOWS = "SET_ON_AIRED_TV_SHOWS";
export const SET_ON_AIRED_TV_SHOWS_REDUCER = "SET_ON_AIRED_TV_SHOWS_REDUCER";

export const GET_ON_AIRED_TV_SHOWS_PAGE_REDUCER =
  "GET_ON_AIRED_TV_SHOWS_PAGE_REDUCER";
export const SET_ON_AIRED_TV_SHOWS_PAGE_REDUCER =
  "SET_ON_AIRED_TV_SHOWS_PAGE_REDUCER";

export const GET_ON_AIRED_TV_SHOWS_TOTAL_PAGES_REDUCER =
  "GET_ON_AIRED_TV_SHOWS_TOTAL_PAGES_REDUCER";
export const SET_ON_AIRED_TV_SHOWS_TOTAL_PAGES_REDUCER =
  "SET_ON_AIRED_TV_SHOWS_TOTAL_PAGES_REDUCER";

export const GET_ON_AIRED_TV_SHOWS_ERROR_REDUCER =
  "GET_ON_AIRED_TV_SHOWS_ERROR_REDUCER";
export const SET_ON_AIRED_TV_SHOWS_ERROR_REDUCER =
  "SET_ON_AIRED_TV_SHOWS_ERROR_REDUCER";

export const GET_AIRING_TODAY_TV_SHOWS = "GET_AIRING_TODAY_TV_SHOWS";
export const GET_AIRING_TODAY_TV_SHOWS_REDUCER =
  "GET_AIRING_TODAY_TV_SHOWS_REDUCER";

export const SET_AIRING_TODAY_TV_SHOWS = "SET_AIRING_TODAY_TV_SHOWS";
export const SET_AIRING_TODAY_TV_SHOWS_REDUCER =
  "SET_AIRING_TODAY_TV_SHOWS_REDUCER";

export const GET_AIRING_TODAY_TV_SHOWS_PAGE_REDUCER =
  "GET_AIRING_TODAY_TV_SHOWS_PAGE_REDUCER";
export const SET_AIRING_TODAY_TV_SHOWS_PAGE_REDUCER =
  "SET_AIRING_TODAY_TV_SHOWS_PAGE_REDUCER";

export const GET_AIRING_TODAY_TV_SHOWS_TOTAL_PAGES_REDUCER =
  "GET_AIRING_TODAY_TV_SHOWS_TOTAL_PAGES_REDUCER";
export const SET_AIRING_TODAY_TV_SHOWS_TOTAL_PAGES_REDUCER =
  "SET_AIRING_TODAY_TV_SHOWS_TOTAL_PAGES_REDUCER";

export const GET_AIRING_TODAY_TV_SHOWS_ERROR_REDUCER =
  "GET_AIRING_TODAY_TV_SHOWS_ERROR_REDUCER";
export const SET_AIRING_TODAY_TV_SHOWS_ERROR_REDUCER =
  "SET_AIRING_TODAY_TV_SHOWS_ERROR_REDUCER";

/* 
  POPULAR PEOPLE TYPES
*/
export const GET_POPULAR_PEOPLE = "GET_POPULAR_PEOPLE";
export const GET_POPULAR_PEOPLE_REDUCER = "GET_POPULAR_PEOPLE_REDUCER";

export const SET_POPULAR_PEOPLE = "SET_POPULAR_PEOPLE";
export const SET_POPULAR_PEOPLE_REDUCER = "SET_POPULAR_PEOPLE_REDUCER";

export const GET_POPULAR_PEOPLE_PAGE_REDUCER =
  "GET_POPULAR_PEOPLE_PAGE_REDUCER";
export const SET_POPULAR_PEOPLE_PAGE_REDUCER =
  "SET_POPULAR_PEOPLE_PAGE_REDUCER";

export const GET_POPULAR_PEOPLE_TOTAL_PAGES_REDUCER =
  "GET_POPULAR_PEOPLE_TOTAL_PAGES_REDUCER";
export const SET_POPULAR_PEOPLE_TOTAL_PAGES_REDUCER =
  "SET_POPULAR_PEOPLE_TOTAL_PAGES_REDUCER";

export const GET_POPULAR_PEOPLE_ERROR_REDUCER =
  "GET_POPULAR_PEOPLE_ERROR_REDUCER";
export const SET_POPULAR_PEOPLE_ERROR_REDUCER =
  "SET_POPULAR_PEOPLE_ERROR_REDUCER";

/* 
  TRENDING TODAY
*/

export const GET_TRENDING_TODAY = "GET_TRENDING_TODAY";
export const GET_TRENDING_TODAY_REDUCER = "GET_TRENDING_TODAY_REDUCER";

export const SET_TRENDING_TODAY = "SET_TRENDING_TODAY";
export const SET_TRENDING_TODAY_REDUCER = "SET_TRENDING_TODAY_REDUCER";

export const GET_TRENDING_TODAY_PAGE_REDUCER =
  "GET_TRENDING_TODAY_PAGE_REDUCER";
export const SET_TRENDING_TODAY_PAGE_REDUCER =
  "SET_TRENDING_TODAY_PAGE_REDUCER";

export const GET_TRENDING_TODAY_TOTAL_PAGES_REDUCER =
  "GET_TRENDING_TODAY_TOTAL_PAGES_REDUCER";
export const SET_TRENDING_TODAY_TOTAL_PAGES_REDUCER =
  "SET_TRENDING_TODAY_TOTAL_PAGES_REDUCER";

export const GET_TRENDING_TODAY_ERROR_REDUCER =
  "GET_TRENDING_TODAY_ERROR_REDUCER";
export const SET_TRENDING_TODAY_ERROR_REDUCER =
  "SET_TRENDING_TODAY_ERROR_REDUCER";

/* 
  TRENDING WEEK
*/

export const GET_TRENDING_WEEK = "GET_TRENDING_WEEK";
export const GET_TRENDING_WEEK_REDUCER = "GET_TRENDING_WEEK_REDUCER";

export const SET_TRENDING_WEEK = "SET_TRENDING_WEEK";
export const SET_TRENDING_WEEK_REDUCER = "SET_TRENDING_WEEK_REDUCER";

export const GET_TRENDING_WEEK_PAGE_REDUCER = "GET_TRENDING_WEEK_PAGE_REDUCER";
export const SET_TRENDING_WEEK_PAGE_REDUCER = "SET_TRENDING_WEEK_PAGE_REDUCER";

export const GET_TRENDING_WEEK_TOTAL_PAGES_REDUCER =
  "GET_TRENDING_WEEK_TOTAL_PAGES_REDUCER";
export const SET_TRENDING_WEEK_TOTAL_PAGES_REDUCER =
  "SET_TRENDING_WEEK_TOTAL_PAGES_REDUCER";

export const GET_TRENDING_WEEK_ERROR_REDUCER =
  "GET_TRENDING_WEEK_ERROR_REDUCER";
export const SET_TRENDING_WEEK_ERROR_REDUCER =
  "SET_TRENDING_WEEK_ERROR_REDUCER";

/* 
  Search
*/

export const GET_SEARCH = "GET_SEARCH";
export const GET_SEARCH_REDUCER = "GET_SEARCH_REDUCER";

export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const SET_SEARCH_RESULT_REDUCER = "SET_SEARCH_RESULT_REDUCER";

export const GET_SEARCH_RESULT_PAGE_REDUCER = "GET_SEARCH_RESULT_PAGE_REDUCER";
export const SET_SEARCH_RESULT_PAGE_REDUCER = "SET_SEARCH_RESULT_PAGE_REDUCER";

export const GET_SEARCH_RESULT_TOTAL_PAGES_REDUCER =
  "GET_SEARCH_RESULT_TOTAL_PAGES_REDUCER";
export const SET_SEARCH_RESULT_TOTAL_PAGES_REDUCER =
  "SET_SEARCH_RESULT_TOTAL_PAGES_REDUCER";

export const GET_SEARCH_RESULT_ERROR_REDUCER =
  "GET_SEARCH_RESULT_ERROR_REDUCER";
export const SET_SEARCH_RESULT_ERROR_REDUCER =
  "SET_SEARCH_RESULT_ERROR_REDUCER";

export const CLEAR_SEARCH_RESULT_REDUCER = "CLEAR_SEARCH_RESULT_REDUCER";

/* 
  Detail
*/

export const GET_DETAILS = "GET_DETAILS";
export const GET_DETAILS_REDUCER = "GET_DETAILS_REDUCER";

export const SET_DETAILS_REDUCER = "SET_DETAILS_REDUCER";

export const GET_DETAILS_ERROR_REDUCER = "GET_DETAILS_ERROR_REDUCER";
export const SET_DETAILS_ERROR_REDUCER = "SET_DETAILS_ERROR_REDUCER";

export const CLEAR_DETAILS_REDUCER = "CLEAR_DETAILS_REDUCER";
/* 
  Details Reviews
*/

export const GET_DETAILS_REVIEWS = "GET_DETAILS_REVIEWS";

export const GET_DETAILS_REVIEWS_REDUCER = "GET_DETAILS_REVIEWS_REDUCER";
export const SET_DETAILS_REVIEWS_REDUCER = "SET_DETAILS_REVIEWS_REDUCER";

export const GET_DETAILS_REVIEWS_PAGE_REDUCER =
  "GET_DETAILS_REVIEWS_PAGE_REDUCER";
export const SET_DETAILS_REVIEWS_PAGE_REDUCER =
  "SET_DETAILS_REVIEWS_PAGE_REDUCER";

export const GET_DETAILS_REVIEWS_TOTAL_PAGES_REDUCER =
  "GET_SEARCHDETAILS_REVIEWS_PAGES_REDUCER";
export const SET_DETAILS_REVIEWS_TOTAL_PAGES_REDUCER =
  "SET_DETAILS_REVIEWS_TOTAL_PAGES_REDUCER";

export const GET_DETAILS_REVIEWS_ERROR_REDUCER =
  "GET_DETAILS_REVIEWS_ERROR_REDUCER";
export const SET_DETAILS_REVIEWS_ERROR_REDUCER =
  "SET_DETAILS_REVIEWS_ERROR_REDUCER";
